server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shankar-Aware07/microservice-config
          clone-on-start: true